import type { SupabaseClient } from "@supabase/supabase-js";
import { calculateConfidence,calculateNewMastery,normalizeAdaptiveDifficulty,resolveDifficultyByMastery } from "@/lib/adaptive-engine/mastery";
import { chooseAdaptiveAction,recommendationMessages } from "@/lib/adaptive-engine/recommendation";
import { calculateNextReviewDate } from "@/lib/adaptive-engine/review-scheduler";
export type RecordSkillMasteryInput={supabase:SupabaseClient;studentId:string;skillCodes:string[];isCorrect:boolean;difficulty?:string|null;hintCount?:number;attemptNumber?:number;entityId?:string|null;entityType?:string};
export async function recordSkillMasteryForCodes(input:RecordSkillMasteryInput){
 const codes=[...new Set(input.skillCodes.filter(Boolean))]; if(!codes.length)return {updatedSkills:[],action:"continue_same_level" as const,message:recommendationMessages.continue_same_level};
 const {data:skills,error:skillsError}=await input.supabase.from("skills").select("id, code, title, is_critical").in("code",codes); if(skillsError||!skills?.length)return null;
 const ids=skills.map(s=>s.id); const {data:existing}=await input.supabase.from("student_skill_mastery").select("*").eq("student_id",input.studentId).in("skill_id",ids);
 const bySkill=new Map((existing??[]).map(row=>[row.skill_id,row])); const difficulty=normalizeAdaptiveDifficulty(input.difficulty); const rows=skills.map(skill=>{const old=bySkill.get(skill.id);const total=(old?.total_attempts??0)+1;const correct=(old?.correct_attempts??0)+(input.isCorrect?1:0);const mastery=calculateNewMastery({oldMastery:Number(old?.mastery_score??0),isCorrect:input.isCorrect,difficulty,hintCount:input.hintCount??0,attemptNumber:input.attemptNumber??1,skillWeight:1});return {student_id:input.studentId,skill_id:skill.id,mastery_score:mastery,confidence:calculateConfidence(total),current_level:resolveDifficultyByMastery(mastery),total_attempts:total,correct_attempts:correct,consecutive_correct:input.isCorrect?(old?.consecutive_correct??0)+1:0,consecutive_wrong:input.isCorrect?0:(old?.consecutive_wrong??0)+1,hints_used:(old?.hints_used??0)+(input.hintCount??0),last_practiced_at:new Date().toISOString(),next_review_at:calculateNextReviewDate(mastery).toISOString(),updated_at:new Date().toISOString()};});
 const {data:updated,error:updateError}=await input.supabase.from("student_skill_mastery").upsert(rows,{onConflict:"student_id,skill_id"}).select("*, skill:skill_id(code,title,is_critical)"); if(updateError||!updated)return null;
 const scores=updated.map(r=>Number(r.mastery_score)); const weak=Math.min(...scores); const critical=updated.filter(r=>r.skill?.is_critical).map(r=>Number(r.mastery_score)); const maxWrong=Math.max(...updated.map(r=>Number(r.consecutive_wrong??0))); const maxAttempts=Math.max(...updated.map(r=>Number(r.total_attempts??0)));
 const action=chooseAdaptiveAction({finalTopicScore:weak,criticalSkillMinScore:critical.length?Math.min(...critical):100,prerequisiteMinScore:100,totalAttemptsForWeakSkill:maxAttempts,weakSkillScore:weak,consecutiveWrong:maxWrong,recentAttemptsCount:maxAttempts});
 await input.supabase.from("learning_events").insert({student_id:input.studentId,event_type:input.isCorrect?"task_correct":"task_wrong",entity_type:input.entityType??"task_pack_item",entity_id:input.entityId??null,metadata:{skillCodes:codes,action,difficulty}});
 if(action==="show_remediation"||action==="teacher_attention_required"){const target=updated.sort((a,b)=>Number(a.mastery_score)-Number(b.mastery_score))[0];await input.supabase.from("adaptive_recommendations").insert({student_id:input.studentId,skill_id:target.skill_id,recommendation_type:action,reason:recommendationMessages[action],payload:{source:input.entityType??"task_pack_item"}});}
 return {updatedSkills:updated,action,message:recommendationMessages[action]};
}
