import { redirect } from "next/navigation";
import { AppShell } from "@/components/layout/AppShell";
import { CinematicAnalytics } from "@/components/analytics/CinematicAnalytics";
import { Badge } from "@/components/ui/Badge";
import { Card,CardText,CardTitle } from "@/components/ui/Card";
import { getTeacherAdaptiveSnapshot,type StudentAdaptiveSnapshot } from "@/lib/adaptive-engine/queries";
import { getCurrentProfile } from "@/lib/auth";
import { getMyStudents } from "@/lib/db";
export default async function TeacherAnalyticsPage(){const profile=await getCurrentProfile();if(!profile)redirect("/login");if(profile.role!=="teacher"&&profile.role!=="admin")redirect("/dashboard");const students=await getMyStudents(profile.id);const aggregate=await getTeacherAdaptiveSnapshot(students.map(s=>s.id));const snapshot:StudentAdaptiveSnapshot={skills:aggregate.skills,recommendations:[],reviews:[],events:aggregate.events,labs:aggregate.labs,packAttempts:aggregate.packAttempts};return <AppShell profile={profile} active="/teacher/analytics"><div className="page-stack"><CinematicAnalytics snapshot={snapshot} teacherMode title="Сынып аналитикасы"/><section className="grid gap-3 lg:grid-cols-[1fr_.7fr]"><Card><CardTitle>Оқушы мәртебелері</CardTitle><div className="mt-3 space-y-2">{students.length?students.map(student=>{const skills=aggregate.skills.filter(s=>s.student_id===student.id);const score=skills.length?Math.round(skills.reduce((sum,s)=>sum+Number(s.mastery_score),0)/skills.length):0;return <div key={student.id} className="flex items-center justify-between gap-3 border-b border-[var(--border-soft)] pb-2"><div><p className="text-xs font-black text-[var(--text)]">{student.full_name}</p><p className="mt-1 text-[11px] text-[var(--text-muted)]">{student.current_grade??"—"}-сынып · {skills.length} skill</p></div><Badge variant={score>=80?"success":score>=60?"warning":"danger"}>{score}%</Badge></div>}):<CardText>Оқушылар тіркелгеннен кейін салыстырмалы аналитика шығады.</CardText>}</div></Card><Card><CardTitle>Тексеру жүктемесі</CardTitle><div className="mt-3 space-y-2">{[["Қолмен тексеру",aggregate.manualReviewCount,"warning"],["Adaptive сигнал",aggregate.recommendationCount,"primary"],["Зертхана",aggregate.labs.length,"cyan"],["Әрекет журналы",aggregate.events.length,"default"]].map(([label,value,variant])=><div key={String(label)} className="flex items-center justify-between border-b border-[var(--border-soft)] pb-2 text-xs"><span className="font-extrabold text-[var(--text-soft)]">{String(label)}</span><Badge variant={variant as "warning"|"primary"|"cyan"|"default"}>{String(value)}</Badge></div>)}</div></Card></section></div></AppShell>}
