import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, Beaker, BookOpenCheck, Calculator, ClipboardCheck, Filter, FlaskConical, Layers3, Sparkles } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card,CardText,CardTitle } from "@/components/ui/Card";
import { PageHeader } from "@/components/ui/PageHeader";
import { getCurrentProfile,getRoleHomePath } from "@/lib/auth";
import { getStudentPackAttempts,getTaskPacks } from "@/lib/taskPacks";
type Props={searchParams:Promise<{grade?:string}>};
const grades=[7,8,9,10,11];
function parseGrade(value?:string){const number=Number(value);return grades.includes(number)?number:7}
export default async function TasksPage({searchParams}:Props){const query=await searchParams;const selectedGrade=parseGrade(query.grade);const profile=await getCurrentProfile();if(!profile)redirect("/login");if(profile.role!=="student")redirect(getRoleHomePath(profile.role));if(!profile.teacher_id)redirect("/onboarding/teacher-select");if(!profile.diagnostic_completed)redirect("/onboarding/diagnostic");if(!profile.onboarding_completed)redirect("/onboarding/interests");const [packs,attempts]=await Promise.all([getTaskPacks(selectedGrade),getStudentPackAttempts(profile.id)]);return <AppShell profile={profile} active="/tasks"><div className="page-stack">
 <PageHeader eyebrow="Тапсырмалар" title="Кешенді физика тапсырмалары" description="Әр сыныпта 10 күрделі жұмыс бар. Әр жұмыстың ішінде 10 тест, 5 есеп және 1 зертханалық немесе практикалық тапсырма беріледі." actions={<Button href="/topics" variant="secondary" size="sm"><BookOpenCheck className="h-4 w-4"/>Оқу бағдарламасы</Button>}/>
 <Card className="science-panel border-[var(--border-accent)]"><div className="relative grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[4px] bg-[var(--purple-soft)] text-[var(--primary)]"><Sparkles className="h-5 w-5"/></span><div><p className="data-label text-[var(--primary)]">Adaptive task system</p><h2 className="mt-1 text-base font-black text-[var(--text)]">Жай тест емес — толық оқу циклі</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-[var(--text-muted)]">Тест ұғымды тексереді, есеп формуланы нақты жағдайда қолдануға үйретеді, ал зертхана өлшеу, график және қорытынды дағдыларын дамытады.</p></div></div><Button href={`/tasks/packs/${packs[0]?.slug??"g7-measurement"}`}>Бірінші жұмысты ашу <ArrowRight className="h-4 w-4"/></Button></div></Card>
 <Card className="p-3"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-[var(--primary)]"/><p className="text-sm font-black text-[var(--text)]">Сыныпты таңдаңыз</p></div><div className="flex flex-wrap gap-1.5">{grades.map(grade=><Link key={grade} href={`/tasks?grade=${grade}`} className={`inline-flex h-8 items-center rounded-[4px] border px-3 text-xs font-extrabold transition ${grade===selectedGrade?"border-[var(--primary)] bg-[var(--primary)] text-white":"border-[var(--border)] bg-white text-[var(--text-soft)] hover:bg-[var(--surface-muted)]"}`}>{grade}-сынып</Link>)}</div></div></Card>
 <div className="grid gap-2 sm:grid-cols-4">{[{icon:Layers3,label:"Кешенді жұмыс",value:packs.length},{icon:ClipboardCheck,label:"Тест сұрағы",value:packs.length*10},{icon:Calculator,label:"Есеп шығару",value:packs.length*5},{icon:FlaskConical,label:"Зертхана",value:packs.length}].map(({icon:Icon,label,value})=><Card key={label} className="p-3"><Icon className="h-4 w-4 text-[var(--primary)]"/><p className="mt-2 text-[11px] font-extrabold text-[var(--text-muted)]">{label}</p><p className="mt-1 text-xl font-black text-[var(--text)]">{String(value)}</p></Card>)}</div>
 <section className="grid gap-3 lg:grid-cols-2">{packs.map(pack=>{const packAttempts=attempts.filter(a=>a.pack_id===pack.id);const complete=Math.min(16,new Set(packAttempts.map(a=>a.item_id)).size);const progress=Math.round(complete/16*100);return <Link key={pack.slug} href={`/tasks/packs/${pack.slug}`} className="group"><article className="h-full rounded-[6px] border border-[var(--border)] bg-white p-3 shadow-[var(--shadow-xs)] transition group-hover:-translate-y-0.5 group-hover:border-[var(--border-accent)] group-hover:shadow-[var(--shadow-sm)] sm:p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-1.5"><Badge variant={pack.difficulty==="advanced"?"warning":pack.difficulty==="basic"?"success":"primary"}>{pack.difficulty==="advanced"?"Күрделі":pack.difficulty==="basic"?"Базалық":"Орта деңгей"}</Badge><Badge>{pack.estimated_minutes} мин</Badge>{pack.source==="database"?<Badge variant="cyan">DB</Badge>:<Badge variant="warning">Алдын ала көру</Badge>}</div><h2 className="mt-3 text-base font-black text-[var(--text)]">{pack.order_index}. {pack.title}</h2><p className="mt-1 text-xs font-extrabold text-[var(--primary)]">{pack.formula}</p></div><span className="grid h-9 w-9 place-items-center rounded-[4px] bg-[var(--purple-soft)] text-[var(--primary)]"><Beaker className="h-4 w-4"/></span></div><p className="mt-3 text-sm leading-6 text-[var(--text-muted)]">{pack.description}</p><div className="mt-3 flex flex-wrap gap-1.5"><Badge>10 тест</Badge><Badge>5 есеп</Badge><Badge>1 зертхана</Badge></div><div className="mt-3 border-t border-[var(--border-soft)] pt-3"><div className="flex justify-between text-[11px] font-extrabold text-[var(--text-muted)]"><span>Орындалуы</span><span>{progress}%</span></div><div className="mt-1.5 h-1.5 overflow-hidden bg-[var(--surface-muted)]"><div className="h-full bg-[var(--primary)]" style={{width:`${progress}%`}}/></div></div></article></Link>})}</section>
 <Card className="border-dashed"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>Тақырыптық адаптивті сессия сақталды</CardTitle><CardText className="mt-1">Бұрынғы оқу ағыны өшірілген жоқ. Тақырып ішіндегі қысқа сессияларды оқу бағдарламасы арқылы ашуға болады.</CardText></div><Button href="/topics" variant="ghost">Тақырыптарға өту <ArrowRight className="h-4 w-4"/></Button></div></Card>
 </div></AppShell>}
