import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, Search, UsersRound } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Badge } from "@/components/ui/Badge";
import { Card,CardText,CardTitle } from "@/components/ui/Card";
import { PageHeader } from "@/components/ui/PageHeader";
import { getCurrentProfile } from "@/lib/auth";
import { getMyStudents } from "@/lib/db";
export default async function TeacherStudentsPage(){const profile=await getCurrentProfile();if(!profile)redirect("/login");if(profile.role!=="teacher"&&profile.role!=="admin")redirect("/dashboard");const students=await getMyStudents(profile.id);return <AppShell profile={profile} active="/teacher/students"><div className="page-stack"><PageHeader eyebrow="Оқушылар" title="Менің оқушыларым" description="Әр оқушының диагностикасын, skill mastery картасын, соңғы әрекеттерін және зертхана нәтижелерін қараңыз."/><Card className="p-3"><div className="flex h-9 items-center gap-2 rounded-[4px] border border-[var(--border)] bg-[var(--surface-muted)] px-3 text-xs text-[var(--text-muted)]"><Search className="h-3.5 w-3.5"/>Оқушыны аты немесе email арқылы іздеу интерфейсі</div></Card><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{students.map(student=><Link key={student.id} href={`/teacher/students/${student.id}`} className="group"><Card className="h-full transition group-hover:-translate-y-0.5 group-hover:border-[var(--border-accent)] group-hover:shadow-[var(--shadow-sm)]"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-[4px] bg-[var(--purple-soft)] text-sm font-black text-[var(--primary)]">{student.full_name.slice(0,1).toUpperCase()}</span><ArrowRight className="h-4 w-4 text-[var(--text-muted)] transition group-hover:text-[var(--primary)]"/></div><CardTitle className="mt-3">{student.full_name}</CardTitle><CardText className="mt-1 text-xs">{student.email||"Email көрсетілмеген"}</CardText><div className="mt-3 flex flex-wrap gap-1.5"><Badge>{student.current_grade??"—"}-сынып</Badge><Badge variant={student.diagnostic_completed?"success":"warning"}>{student.diagnostic_completed?"Диагностика өтті":"Диагностика күтілуде"}</Badge></div></Card></Link>)}</div>{!students.length?<Card><span className="grid h-10 w-10 place-items-center rounded-[4px] bg-[var(--purple-soft)] text-[var(--primary)]"><UsersRound className="h-5 w-5"/></span><CardTitle className="mt-3">Оқушы әзірге жоқ</CardTitle><CardText className="mt-1">Оқушы тіркеліп, сізді мұғалім ретінде таңдағаннан кейін осы жерде көрінеді.</CardText></Card>:null}</div></AppShell>}
