import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, Atom, BarChart3, Beaker, BookOpenCheck, BrainCircuit, CalendarClock, ClipboardCheck, FlaskConical, Gauge, PlayCircle, Sparkles, Target, TrendingUp } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card,CardText,CardTitle } from "@/components/ui/Card";
import { getStudentAdaptiveSnapshot } from "@/lib/adaptive-engine/queries";
import { getCurrentProfile,getStudentEntryPath } from "@/lib/auth";
import { getStudentPackAttempts,getTaskPacks } from "@/lib/taskPacks";
function avg(items:number[]){return items.length?Math.round(items.reduce((a,b)=>a+b,0)/items.length):0}
export default async function DashboardPage(){const profile=await getCurrentProfile();if(!profile)redirect("/login");const entry=getStudentEntryPath(profile);if(entry!=="/dashboard")redirect(entry);const grade=profile.current_grade??7;const [snapshot,packs,packAttempts]=await Promise.all([getStudentAdaptiveSnapshot(profile.id),getTaskPacks(grade),getStudentPackAttempts(profile.id)]);const skillScores=snapshot.skills.map(s=>Number(s.mastery_score));const mastery=avg(skillScores);const weak=snapshot.skills.filter(s=>Number(s.mastery_score)<70).sort((a,b)=>Number(a.mastery_score)-Number(b.mastery_score));const attemptedIds=new Set(packAttempts.map(a=>a.item_id));const continuePack=packs.find(p=>packAttempts.some(a=>a.pack_id===p.id))??packs[0];const correct=packAttempts.filter(a=>a.is_correct===true).length;const autoChecked=packAttempts.filter(a=>a.is_correct!==null).length;const accuracy=autoChecked?Math.round(correct/autoChecked*100):0;return <AppShell profile={profile} active="/dashboard"><div className="page-stack">
 <section className="relative overflow-hidden rounded-[7px] border border-white/10 bg-[var(--navy)] p-4 text-white shadow-[0_16px_40px_rgba(7,21,34,.18)] sm:p-5"><div className="absolute inset-0 physics-grid opacity-20"/><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-[#5747e7]/35 blur-3xl"/><div className="relative grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.18em] text-[#a9a1ff]"><Atom className="h-3.5 w-3.5"/>Student physics cockpit</div><h1 className="mt-2 text-2xl font-black tracking-[-.035em] sm:text-3xl">Сәлем, {profile.full_name.split(" ")[0]}!</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/62">Бүгінгі мақсат — бір күрделі жұмысты жалғастыру және әлсіз дағдыны қысқа тәжірибемен бекіту.</p><div className="mt-4 flex flex-wrap gap-2"><Button href={continuePack?`/tasks/packs/${continuePack.slug}`:"/tasks"}>Оқуды жалғастыру <ArrowRight className="h-4 w-4"/></Button><Button href="/analytics" variant="ghost" className="border-white/15 bg-white/8 text-white hover:bg-white/14"><BarChart3 className="h-4 w-4"/>Аналитика</Button></div></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-2">{[{icon:Gauge,label:"Mastery",value:`${mastery}%`},{icon:Target,label:"Дәлдік",value:`${accuracy}%`},{icon:ClipboardCheck,label:"Орындалған",value:attemptedIds.size},{icon:FlaskConical,label:"Зертхана",value:snapshot.labs.length}].map(({icon:Icon,label,value})=><div key={label} className="min-w-[112px] rounded-[4px] border border-white/12 bg-white/7 p-2.5 backdrop-blur"><Icon className="h-3.5 w-3.5 text-[#93c5fd]"/><p className="mt-2 text-[9px] font-black uppercase tracking-[.12em] text-white/42">{label}</p><p className="mt-0.5 text-lg font-black">{String(value)}</p></div>)}</div></div></section>
 <section className="grid gap-3 lg:grid-cols-[1.15fr_.85fr]"><Card className="science-panel"><div className="relative flex items-start justify-between gap-3"><div><p className="data-label text-[var(--primary)]">Жалғастыру</p><CardTitle className="mt-1">{continuePack?.title??"Алғашқы кешенді жұмысты таңдаңыз"}</CardTitle><CardText className="mt-1">{continuePack?.description??"Тапсырмалар бөлімінде сыныпқа арналған оқу бағыты ашылады."}</CardText></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[4px] bg-[var(--purple-soft)] text-[var(--primary)]"><Sparkles className="h-5 w-5"/></span></div>{continuePack?<><div className="relative mt-4 grid grid-cols-3 gap-2">{[["10","Тест"],["5","Есеп"],["1","Зертхана"]].map(([value,label])=><div key={label} className="rounded-[4px] border border-[var(--border)] bg-white p-2.5"><b className="text-lg text-[var(--text)]">{value}</b><p className="text-[10px] font-black uppercase tracking-[.12em] text-[var(--text-muted)]">{label}</p></div>)}</div><Button href={`/tasks/packs/${continuePack.slug}`} className="relative mt-3">Жұмысты ашу <ArrowRight className="h-4 w-4"/></Button></>:null}</Card><Card><div className="flex items-center gap-2"><BrainCircuit className="h-4 w-4 text-[var(--primary)]"/><CardTitle>Adaptive ұсыныс</CardTitle></div>{snapshot.recommendations.length?<div className="mt-3 space-y-2">{snapshot.recommendations.slice(0,3).map(item=><div key={item.id} className="border-l-2 border-[var(--primary)] bg-[var(--purple-soft)] px-2.5 py-2"><p className="text-xs font-black text-[var(--text)]">{item.skill?.title??"Келесі қадам"}</p><p className="mt-1 text-[11px] leading-5 text-[var(--text-soft)]">{item.reason}</p></div>)}</div>:<p className="mt-3 text-xs leading-5 text-[var(--text-muted)]">Алғашқы тапсырмаларды орындаңыз. Жүйе жауаптарыңызға қарай жеке ұсыныс қалыптастырады.</p>}</Card></section>
 <section className="grid gap-3 lg:grid-cols-3"><Card><div className="flex items-center gap-2"><TrendingUp className="h-4 w-4 text-[var(--warning)]"/><CardTitle>Әлсіз дағдылар</CardTitle></div><div className="mt-3 space-y-2">{weak.length?weak.slice(0,4).map(skill=><div key={skill.id} className="flex items-center justify-between gap-2 border-b border-[var(--border-soft)] pb-2 text-xs"><span className="font-extrabold text-[var(--text-soft)]">{skill.skill?.title}</span><Badge variant={Number(skill.mastery_score)<60?"danger":"warning"}>{Math.round(Number(skill.mastery_score))}%</Badge></div>):<p className="text-xs leading-5 text-[var(--text-muted)]">Дағды картасы тапсырмалар орындалғаннан кейін толтырылады.</p>}</div></Card><Card><div className="flex items-center gap-2"><CalendarClock className="h-4 w-4 text-[var(--blue)]"/><CardTitle>Қайталау кезегі</CardTitle></div><div className="mt-3 space-y-2">{snapshot.reviews.length?snapshot.reviews.slice(0,4).map(review=><div key={review.id} className="border-l-2 border-[var(--blue)] bg-[var(--blue-soft)] px-2.5 py-2"><p className="text-xs font-black text-[var(--text)]">{review.skill?.title??"Дағдыны қайталау"}</p><p className="mt-1 text-[11px] text-[var(--text-muted)]">{new Date(review.scheduled_at).toLocaleDateString("kk-KZ")}</p></div>):<p className="text-xs leading-5 text-[var(--text-muted)]">Жоспарланған қайталау әзірге жоқ.</p>}</div></Card><Card><div className="flex items-center gap-2"><Beaker className="h-4 w-4 text-[var(--cyan)]"/><CardTitle>Ұсынылған зертхана</CardTitle></div><p className="mt-3 text-xs leading-5 text-[var(--text-muted)]">Формуланы тек есеппен емес, параметрлерді өзгерту және график құру арқылы бекітіңіз.</p><Button href="/labs" variant="secondary" size="sm" className="mt-3">Зертханаларға өту <ArrowRight className="h-3.5 w-3.5"/></Button></Card></section>
 <section><div className="mb-3 flex items-end justify-between gap-3"><div><p className="data-label text-[var(--primary)]">Жылдам өту</p><h2 className="mt-1 text-lg font-black text-[var(--text)]">Негізгі бөлімдер</h2></div></div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{[{icon:BookOpenCheck,title:"Оқу бағдарламасы",text:"Теория, формула және шешілген мысал",href:"/topics"},{icon:ClipboardCheck,title:"Тапсырмалар",text:"Күрделі кешенді жұмыстар",href:"/tasks"},{icon:PlayCircle,title:"Видео сабақтар",text:"Сынып бойынша қысқа түсіндірулер",href:"/videos"},{icon:FlaskConical,title:"Зертханалар",text:"2D модель және өлшеу кестесі",href:"/labs"}].map(({icon:Icon,title,text,href})=><Link key={href} href={href}><Card className="h-full transition hover:border-[var(--border-accent)] hover:shadow-[var(--shadow-sm)]"><Icon className="h-4 w-4 text-[var(--primary)]"/><h3 className="mt-3 text-sm font-black text-[var(--text)]">{title}</h3><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">{text}</p></Card></Link>)}</div></section>
 </div></AppShell>}
